export { MessageInput } from './components/MessageInput';

export { AudioRecorderView } from './components/AudioRecorderView';

export { MessageInputMoreDialog, MenuItem } from './components/MessageInputMoreDialog';

export { MinimalistInputBar, MinimalistInputBarCallbacks } from './components/MinimalistInputBar';

export { ClassicInputBar, ClassicInputBarCallbacks } from './components/ClassicInputBar';

// Export styles and types
export { 
  InputStyle,
  ExpandPanelType,
  MessageInputConfigProtocol,
  ChatMessageInputConfig,
} from './config/MessageInputConfig';